# Generated by Django 3.2.3 on 2021-05-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default='hey', max_length=500),
        ),
    ]
